# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_text', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('img_source', models.CharField(max_length=200)),
            ],
        ),
    ]
