# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import slides.models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdffile',
            field=models.FileField(default=b'', upload_to=slides.models.rename),
        ),
    ]
