# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slides', '0002_slides_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='slides',
            name='votes',
        ),
        migrations.AddField(
            model_name='votes',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Slides'),
        ),
        migrations.AddField(
            model_name='votes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
