# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_auto_20160601_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdffile',
            field=models.FileField(upload_to=b'media'),
        ),
    ]
