# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0004_auto_20160530_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
