# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_auto_20160602_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdffile',
            field=models.FileField(upload_to=b'courses'),
        ),
    ]
