# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0006_auto_20160602_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='lecture',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
