# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import slides.models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0006_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='docfile',
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdffile',
            field=models.FileField(default=b'', upload_to=slides.models.rename),
        ),
    ]
