# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import slides.models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0007_auto_20160531_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdffile',
            field=models.FileField(default=b'uploads', upload_to=slides.models.rename),
        ),
    ]
