# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0012_question_question_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name=b'Question'),
        ),
    ]
