# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0015_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='course',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='lecturer',
        ),
    ]
